name: Bitcoin Improvement Proposal Gallery
pygments: true
permalink: /:year/:month/:title/
url: https://prayank23.github.io/BIPsGallery/
author:
    name: Prayank
    twitter: https://twitter.com/prayankgahlot
